/*
**** *******Problem Statement**********

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/



// Method: store last two values then add to sum

#include <stdio.h>

int main(){
    int current_number = 1;
    int previous_number = 0;
    int tmp = 0;
    int sum = 0;

    while( current_number <= 4000000){
        tmp = current_number;
        current_number = current_number + previous_number;
        previous_number = tmp;

        if (current_number % 2 == 0){
            sum = sum + current_number;
        }
    }

    printf("proccess finished ! total sum of even fib numbers that don't exceed 4 million: %i \n", sum);
    
}